### ISSUE TITLE
Explain the point of this repository

### ISSUE THREAD

**Issue by rodislav** [adobe-research/ActionScript4#2]
I guess there are a lot of guys who would like to know what is the point of this repository !?

**Comment by phohensee** [comment]
See the readme

https://github.com/adobe-research/ActionScript4/blob/master/README.md

On Wed, Jan 22, 2014 at 4:39 PM, Rodislav Moldovan <notifications@github.com

**Comment by rodislav** [comment]
"may be considered incomplete. Source code for the compiler and runtime is not available. Adobe has no plans to resume development of ActionScript 4."

yes, and the point is.. !?  "the hope that they may be useful to"

a bunch of incomplete files !?  ... useful !? ... no source code..

ps. I'm not angry or against any one.. I simply don't see a reason why adobe need to hurt flash developer's feelings :(

**Comment by gsynuh** [comment]
Every file here is complete as far as I know, we've got the .tex files and the .pdfs

**Comment by gsynuh** [comment]
I'd like to quote Josh Tynjala (if he doesn't mind) . A thought he shared on the Starling forums which I share but can't phrase better :
"I think it just means that they decided to share their research so that it won't completely go to waste. "

**Comment by rodislav** [comment]
maybe, but I'm to skeptical :-(  

linus torvalds said: "talk is cheap, show me the code"

in this repo.. they simply give us "the talk", while the true power stays in the code

**Comment by gsynuh** [comment]
Being a very new developer, I find that very cool that a company as big as this one would share its research in this form, much like I enjoy universities sharing courses and lectures online for example 

I'd follow the "knowledge is power" phrase instead ... or "give a man a fish..." . 

There are probably a lot of good reasons not to expose their prototype compiler/runtime/VM or whatever.
mostly economical or political (in the absolute sense) . And maybe it contains too much info/data on the current AS3 products which could hurt them (economically)  because after all as4 was not a start from scratch deal if I understood correctly.

I do understand your point of view even though I do not share it completely.
I guess I may not have enough experience/time to have' my feelings hurt'

**Comment by rodislav** [comment]
yes, but nowadays not very much people are studying Latin, there are plenty of fully open source languages in development and in use. The only good thing people should learn from adobe is --> how to not kill wonderful platform
